export const episode_list = [
    { label: "Encounter at Farpoint" },
    { label: "The Naked Now" },
    { label: "Code of Honor" },
    { label: "Haven" },
    { label: "Where No One Has Gone Before" },
    { label: "The Last Outpost" },
    { label: "Lonely Among Us" },
    { label: "Justice" },
    { label: "The Battle" },
    { label: "Hide and Q" },
    { label: "Too Short a Season" },
    { label: "The Big Goodbye" },
    { label: "Datalore" },
    { label: "Angel One" },
    { label: "11001001" },
    { label: "Home Soil" },
    { label: "When the Bough Breaks" },
    { label: "Coming of Age" },
    { label: "Heart of Glory" },
    { label: "The Arsenal of Freedom" },
    { label: "Skin of Evil" },
    { label: "Symbiosis" },
    { label: "We'll Always Have Paris" },
    { label: "Conspiracy" },
    { label: "The Neutral Zone" },
    { label: "The Child" },
    { label: "Where Silence Has Lease" },
    { label: "Elementary,  Dear Data" },
    { label: "The Outrageous Okona" },
    { label: "The Schizoid Man" },
    { label: "Loud as a Whisper" },
    { label: "Unnatural Selection" },
    { label: "A Matter of Honor" },
    { label: "The Measure of a Man" },
    { label: "The Dauphin" },
    { label: "Contagion" },
    { label: "The Royale" },
    { label: "Time Squared" },
    { label: "The Icarus Factor" },
    { label: "Pen Pals" },
    { label: "Q Who?" },
    { label: "Samaritan Snare" },
    { label: "Up the Long Ladder" },
    { label: "Manhunt" },
    { label: "The Emissary" },
    { label: "Peak Performance" },
    { label: "Shades of Gray" },
    { label: "The Ensigns of Command" },
    { label: "Evolution" },
    { label: "The Survivors" },
    { label: "Who Watches the Watchers" },
    { label: "The Bonding" },
    { label: "Booby Trap" },
    { label: "The Enemy" },
    { label: "The Price" },
    { label: "The Vengeance Factor" },
    { label: "The Defector" },
    { label: "The Hunted" },
    { label: "The High Ground" },
    { label: "Deja Q" },
    { label: "A Matter of Perspective" },
    { label: "Yesterday's Enterprise" },
    { label: "The Offspring" },
    { label: "Sins of the Father" },
    { label: "Allegiance" },
    { label: "Captain's Holiday" },
    { label: "Tin Man" },
    { label: "Hollow Pursuits" },
    { label: "The Most Toys" },
    { label: "Sarek" },
    { label: "Ménage à Troi" },
    { label: "Transfigurations" },
    { label: "The Best of Both Worlds: Part 1" },
    { label: "The Best of Both Worlds: Part 2" },
    { label: "Suddenly Human" },
    { label: "Brothers" },
    { label: "Family" },
    { label: "Remember Me" },
    { label: "Legacy" },
    { label: "Reunion" },
    { label: "Final Mission" },
    { label: "The Loss" },
    { label: "Data's Day" },
    { label: "The Wounded" },
    { label: "Devil's Due" },
    { label: "Clues" },
    { label: "First Contact" },
    { label: "Galaxy's Child" },
    { label: "Night Terrors" },
    { label: "Identity Crisis" },
    { label: "The NTH Degree" },
    { label: "Qpid" },
    { label: "The Drumhead" },
    { label: "Half a Life" },
    { label: "The Host" },
    { label: "The Mind's Eye" },
    { label: "In Theory" },
    { label: "Redemption" },
    { label: "Redemption Ii" },
    { label: "Darmok" },
    { label: "Ensign Ro" },
    { label: "Silicon Avatar" },
    { label: "Disaster" },
    { label: "The Game" },
    { label: "Unification Part 2" },
    { label: "Unification Part 1" },
    { label: "A Matter of Time" },
    { label: "New Ground" },
    { label: "Hero Worship" },
    { label: "Violations" },
    { label: "The Masterpiece Society" },
    { label: "Conundrum" },
    { label: "Power Play" },
    { label: "Ethics" },
    { label: "The Outcast" },
    { label: "Cause and Effect" },
    { label: "The First Duty" },
    { label: "Cost of Living" },
    { label: "The Perfect Mate" },
    { label: "Imaginary Friend" },
    { label: "I Borg" },
    { label: "The Next Phase" },
    { label: "The Inner Light" },
    { label: "Time's Arrow" },
    { label: "Time's Arrow: Part 2" },
    { label: "Realm of Fear" },
    { label: "Man of the People" },
    { label: "Relics" },
    { label: "Schisms" },
    { label: "True Q" },
    { label: "Rascals" },
    { label: "A Fistful of Datas" },
    { label: "The Quality of Life" },
    { label: "Chain of Command: Part 1" },
    { label: "Chain of Command: Part 2" },
    { label: "Ship in a Bottle" },
    { label: "Aquiel" },
    { label: "Face of the Enemy" },
    { label: "Tapestry" },
    { label: "Birthright: Part 1" },
    { label: "Birthright: Part 2" },
    { label: "Starship Mine" },
    { label: "Lessons" },
    { label: "The Chase" },
    { label: "Frame of Mind" },
    { label: "Suspicions" },
    { label: "Rightful Heir" },
    { label: "Second Chances" },
    { label: "Timescape" },
    { label: "Descent: Part 1" },
    { label: "Descent: Part 2" },
    { label: "Liaisons" },
    { label: "Interface" },
    { label: "Gambit: Part 1" },
    { label: "Gambit: Part 2" },
    { label: "Phantasms" },
    { label: "Dark Page" },
    { label: "Attached" },
    { label: "Force of Nature" },
    { label: "Inheritance" },
    { label: "Parallels" },
    { label: "The Pegasus" },
    { label: "Homeward" },
    { label: "Sub Rosa" },
    { label: "Lower Decks" },
    { label: "Thine Own Self" },
    { label: "Masks" },
    { label: "Eye of the Beholder" },
    { label: "Genesis" },
    { label: "Journey's End" },
    { label: "Firstborn" },
    { label: "Bloodlines" },
    { label: "Emergence" },
    { label: "Preemptive Strike" },
    { label: "All Good Things..." },
]
